# This workflow will build and deploy a package using gradle
name: Gradle Build

on:
  workflow_dispatch:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    - name: Build
      run: |
        ./gradlew clean build publish --stacktrace --refresh-dependencies --gradle-user-home ~/.gradle/
